"use client";

import { useState, type FormEvent } from "react";
import { Button } from "@/components/ui";
import type { AdminUserRow } from "./admin-users";

type ContentRow = { author?: string; category?: string; id: string; ownerEmail?: string; processingStatus: string; title: string; updatedAt: string; visibility: "private" | "public" };
type Draft = { assignedUserId: string; author: string; category: string; text: string; title: string; visibility: "private" | "public" };
const emptyDraft: Draft = { assignedUserId: "", author: "", category: "", text: "", title: "", visibility: "public" };

export function AdminContents({ initialContents, users }: { initialContents: ContentRow[]; users: AdminUserRow[] }) {
  const [contents, setContents] = useState(initialContents); const [draft, setDraft] = useState(emptyDraft);
  const [editing, setEditing] = useState<string | null>(null); const [editDraft, setEditDraft] = useState<Partial<Draft>>({});
  const [status, setStatus] = useState("");
  async function reload() { const response = await fetch("/api/admin/contents"); if (response.ok) setContents(((await response.json()) as { contents: ContentRow[] }).contents); }
  async function create(event: FormEvent) { event.preventDefault(); setStatus("Salvando…"); const response = await fetch("/api/admin/contents", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(draft) }); const body = await response.json(); if (!response.ok) { setStatus(body?.error?.message ?? "Falha ao salvar."); return; } setDraft(emptyDraft); setStatus("Conteúdo criado."); await reload(); }
  async function save(id: string) { setStatus("Salvando…"); const response = await fetch("/api/admin/contents/" + id, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(editDraft) }); const body = await response.json(); if (!response.ok) { setStatus(body?.error?.message ?? "Falha ao salvar."); return; } setEditing(null); setEditDraft({}); setStatus("Conteúdo atualizado."); await reload(); }
  async function remove(item: ContentRow) { if (!confirm(`Excluir definitivamente “${item.title}”?`)) return; const response = await fetch("/api/admin/contents/" + item.id, { method: "DELETE" }); if (!response.ok) { setStatus("Não foi possível excluir."); return; } setStatus("Conteúdo excluído."); await reload(); }
  const userOptions = users.filter((user) => user.status === "active");
  return <section><header className="admin-page-header"><div><p>Biblioteca pública e privada</p><h1>Conteúdos</h1></div></header>
    <form className="admin-content-form admin-panel" onSubmit={create}><h2>Novo conteúdo</h2><div className="admin-form-grid"><label><span>Título</span><input onChange={(e) => setDraft((d) => ({ ...d, title: e.target.value }))} required value={draft.title} /></label><label><span>Autor</span><input onChange={(e) => setDraft((d) => ({ ...d, author: e.target.value }))} value={draft.author} /></label><label><span>Categoria</span><input onChange={(e) => setDraft((d) => ({ ...d, category: e.target.value }))} value={draft.category} /></label><label><span>Visibilidade</span><select onChange={(e) => setDraft((d) => ({ ...d, visibility: e.target.value as Draft["visibility"] }))} value={draft.visibility}><option value="public">Público</option><option value="private">Privado</option></select></label>{draft.visibility === "private" ? <label><span>Usuário autorizado</span><select onChange={(e) => setDraft((d) => ({ ...d, assignedUserId: e.target.value }))} required value={draft.assignedUserId}><option value="">Selecione</option>{userOptions.map((user) => <option key={user.id} value={user.id}>{user.name} — {user.email}</option>)}</select></label> : null}</div><label><span>Texto</span><textarea minLength={20} onChange={(e) => setDraft((d) => ({ ...d, text: e.target.value }))} required rows={8} value={draft.text} /></label><Button type="submit">Cadastrar conteúdo</Button></form>
    <p aria-live="polite">{status}</p><div className="admin-content-list">{contents.map((item) => editing === item.id ? <form className="admin-panel admin-edit-content" key={item.id} onSubmit={(e) => { e.preventDefault(); void save(item.id); }}><input aria-label="Título" defaultValue={item.title} onChange={(e) => setEditDraft((d) => ({ ...d, title: e.target.value }))} /><input aria-label="Autor" defaultValue={item.author} onChange={(e) => setEditDraft((d) => ({ ...d, author: e.target.value }))} /><input aria-label="Categoria" defaultValue={item.category} onChange={(e) => setEditDraft((d) => ({ ...d, category: e.target.value }))} /><select aria-label="Visibilidade" defaultValue={item.visibility} onChange={(e) => setEditDraft((d) => ({ ...d, visibility: e.target.value as Draft["visibility"] }))}><option value="public">Público</option><option value="private">Privado</option></select><select aria-label="Usuário autorizado" defaultValue="" onChange={(e) => setEditDraft((d) => ({ ...d, assignedUserId: e.target.value }))}><option value="">Manter atribuição atual</option>{userOptions.map((user) => <option key={user.id} value={user.id}>{user.name} — {user.email}</option>)}</select><textarea aria-label="Novo texto opcional" onChange={(e) => setEditDraft((d) => ({ ...d, text: e.target.value }))} placeholder="Deixe vazio para manter o texto atual" rows={5} /><div><Button type="submit">Salvar</Button><Button onClick={() => setEditing(null)} type="button" variant="secondary">Cancelar</Button></div></form> : <article className="admin-panel admin-content-row" key={item.id}><div><span className={`status-pill status-${item.visibility}`}>{item.visibility === "public" ? "Público" : "Privado"}</span><h2>{item.title}</h2><p>{item.author || "Autor não informado"} · {item.category || "Sem categoria"}</p>{item.ownerEmail ? <small>Atribuído a {item.ownerEmail}</small> : null}</div><div><Button onClick={() => { setEditing(item.id); setEditDraft({}); }} size="small" variant="secondary">Editar</Button><Button onClick={() => void remove(item)} size="small" variant="danger">Excluir</Button></div></article>)}</div>
  </section>;
}
